---
- name: Create swap file
  command: fallocate -l 4G /swapfile4g
  args:
    creates: /swapfile4g

- name: Set permissions on swap file
  file:
    path: /swapfile4g
    owner: root
    group: root
    mode: '0600'

- name: Make swap
  command: mkswap /swapfile4g
  when: ansible_facts.swapfree_mb < 4096  # 필요 시 조건 조정

- name: Enable swap
  command: swapon /swapfile4g
  register: swapon_result
  failed_when: "'already in use' in swapon_result.stderr"

- name: Add swap to /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: '/swapfile4g none swap sw 0 0'
    state: present

- name: Install dependencies
  dnf:
    name:
      - policycoreutils-python-utils
      - openssh-server
      - openssh-clients
      - perl
    state: present

- name: Enable and start sshd service
  systemd:
    name: sshd
    enabled: yes
    state: started

- name: Add GitLab repo
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh
    dest: /tmp/script.rpm.sh
    mode: '0755'

- name: Run GitLab repo script
  command: /tmp/script.rpm.sh
  args:
    creates: /etc/yum.repos.d/gitlab_gitlab-ce.repo

- name: Install gitlab-ce
  dnf:
    name: gitlab-ce
    state: present

- name: Ensure /etc/gitlab/ssl directory exists
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy CA certificate to gitlab ssl
  copy:
    src: /etc/pki/ca-trust/source/anchors/ca.crt
    dest: /etc/gitlab/ssl/ca.crt
    owner: root
    group: root
    mode: '0644'

- name: Generate /etc/gitlab/gitlab.rb from template
  template:
    src: ../files/gitlab.rb.template.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: '0644'


- name: Reconfigure GitLab
  command: gitlab-ctl reconfigure