- name : Generate Own CA
  hosts: localhost
  become: true
  roles:
    - ca_root

- name : Generate CSR 
  hosts: 
    - harbor
  become: true
  roles:
    - ca_signed

- name : setup init
  hosts: all
  become: true
  roles:
    - setup_init

- name: Install Harbor
  hosts: harbor
  become: true
  vars_files:
    - vars.yml
  roles:
    - harbor
    
- name: Web Server
  hosts: web
  become: true
  vars_files:
    - vars.yml
  roles:
    - web
