- name : Generate Own CA
  hosts: localhost
  become: true
  roles:
    - ca_root

- name : Generate CSR 
  hosts: 
    - gitlab
    - jenkins
    - harbor
  become: true
  roles:
    - ca_signed

- name : setup init
  hosts: all
  become: true
  roles:
    - setup_init

- name: Install Gitlab
  hosts: gitlab
  become: true
  vars_files:
    - vars.yml
  roles:
    - gitlab

- name: Install Jenkins
  hosts: jenkins_controller
  become: true
  vars_files:
    - vars.yml
  roles:
    - jenkins

- name: Setting Jenkins Agent
  hosts: jenkins_agent
  become: true
  roles:
    - agent

- name: Install Harbor
  hosts: harbor
  become: true
  vars_files:
    - vars.yml
  roles:
    - harbor
    
- name: Web Server
  hosts: web
  become: true
  vars_files:
    - vars.yml
  roles:
    - web