# Install oh-my-bash and configure the default theme to 'agnoster'
- name: Install git
  dnf:
    name: git
    state: present

- name: Clone oh-my-bash
  git:
    repo: https://github.com/ohmybash/oh-my-bash.git
    dest: /root/.oh-my-bash
    update: no

- name: Copy default bashrc
  copy:
    src: /root/.oh-my-bash/templates/bashrc.osh-template
    dest: /root/.bashrc
    remote_src: yes

- name: Set theme to agnoster
  lineinfile:
    path: /root/.bashrc
    regexp: '^OSH_THEME='
    line: 'OSH_THEME="agnoster"'

# Add previously created custom CA certificate to system trust store
- name: Copy CA certificate to anchors directory on Amazon Linux 2023
  copy:
    src: /etc/ssl/my_cert/ca.crt   # localhost path (Ansible control node)
    dest: /etc/pki/ca-trust/source/anchors/ca.crt
    owner: root
    group: root
    mode: '0644'

- name: Update CA trust on Amazon Linux 2023
  command: update-ca-trust extract
