- name: Install required packages
  become: true
  yum:
    name:
      - wget
      - fontconfig
    state: present

- name: Add Jenkins repo
  become: true
  get_url:
    url: https://pkg.jenkins.io/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins GPG key
  become: true
  rpm_key:
    key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key
    state: present

- name: Import Corretto GPG key
  become: true
  rpm_key:
    key: https://yum.corretto.aws/corretto.key
    state: present

- name: Add Corretto repo
  become: true
  get_url:
    url: https://yum.corretto.aws/corretto.repo
    dest: /etc/yum.repos.d/corretto.repo

- name: Install Amazon Corretto 21 and Jenkins
  become: true
  yum:
    name:
      - java-21-amazon-corretto
      - jenkins
    state: present

- name: Enable and start Jenkins
  become: true
  systemd:
    name: jenkins
    enabled: true
    state: started
    daemon_reload: yes


- name: Generate PKCS#12 file
  community.crypto.openssl_pkcs12:
    action: export
    path: /var/lib/jenkins/keystore.p12
    privatekey_path: "/etc/ssl/private/jenkins.{{ internal_domain }}.key"
    certificate_path: "/etc/ssl/my_cert/jenkins.{{ internal_domain }}.crt"
    friendly_name: mykey
    passphrase: pwdpwd
    state: present
    owner: jenkins


- name: Create systemd override directory
  become: true
  file:
    path: /etc/systemd/system/jenkins.service.d
    state: directory
    mode: '0755'

- name: Set Jenkins HTTPS environment override
  become: true
  copy:
    dest: /etc/systemd/system/jenkins.service.d/override.conf
    content: |
      [Service]
      Environment="JENKINS_PORT=-1"
      Environment="JENKINS_HTTPS_PORT=8443"
      Environment="JENKINS_HTTPS_KEYSTORE=/var/lib/jenkins/keystore.p12"
      Environment="JENKINS_HTTPS_KEYSTORE_PASSWORD=pwdpwd"

- name: Reload systemd daemon
  become: true
  systemd:
    daemon_reload: true

- name: Restart Jenkins service
  become: true
  systemd:
    name: jenkins
    state: restarted

- name: Ensure /var/lib/jenkins/.ssh directory exists
  file:
    path: /var/lib/jenkins/.ssh
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0700'

- name: Add agent1 SSH key to Jenkins known_hosts
  become: true
  shell: |
    ssh-keyscan -H {{ item }} >> /var/lib/jenkins/.ssh/known_hosts
  loop: "{{ groups['jenkins_agent'] }}"
  args:
    creates: /var/lib/jenkins/.ssh/known_hosts