
- name: Install Docker
  yum:
    name: docker
    state: present
  become: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true
  become: yes

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes
  become: yes

- name: Create Docker CLI plugins directory
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: '0755'
  become: yes

- name: Download Docker Compose binary
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.36.2/docker-compose-linux-x86_64
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: '0755'
  become: yes

- name: Download Harbor installer
  get_url:
    url: https://github.com/goharbor/harbor/releases/download/v2.12.3/harbor-online-installer-v2.12.3.tgz
    dest: /tmp/harbor-online-installer-v2.12.3.tgz
  become: yes

- name: Extract Harbor installer
  unarchive:
    src: /tmp/harbor-online-installer-v2.12.3.tgz
    dest: /opt/
    remote_src: yes
    creates: /opt/harbor
  become: yes

- name: Convert .crt (PEM) to .cert (PEM)
  community.crypto.x509_certificate_convert:
    src_path: "/etc/ssl/my_cert/harbor.{{ internal_domain }}.crt"
    dest_path: "/etc/ssl/my_cert/harbor.{{ internal_domain }}.cert"
    format: pem


- name: Ensure docker cert directory exists
  file:
    path: "/etc/docker/certs.d/harbor.{{ internal_domain }}"
    state: directory
    mode: '0755'

- name: Copy certs within the remote server
  shell: cp "{{ item.src }}" "/etc/docker/certs.d/harbor.{{ internal_domain }}/{{ item.dest }}"
  loop:
    - { src: "/etc/ssl/my_cert/harbor.{{ internal_domain }}.cert", dest: "harbor.{{ internal_domain }}.cert" }
    - { src: "/etc/ssl/private/harbor.{{ internal_domain }}.key", dest: "harbor.{{ internal_domain }}.key" }
    - { src: "/etc/pki/ca-trust/source/anchors/ca.crt", dest: "ca.crt" }

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
    enabled: true


- name: Copy harbor.yml from template
  template:
    src: ../files/harbor.yml.template.j2
    dest: /opt/harbor/harbor.yml
    mode: '0644'
  become: yes

- name: Run prepare script
  command: ./prepare
  args:
    chdir: /opt/harbor
  become: yes

- name: Run install script
  command: ./install.sh
  args:
    chdir: /opt/harbor
  become: yes